### ISSUE TITLE
Support des array de strings contrôlées dans TableSchema

### ISSUE THREAD

**Issue by ColinMaudry** [betagouv/data-inclusion-schema#8]
Avec @vmttn nous avions une question concernant la possibilité dans TableSchema de contrôler les valeurs (`enum`) dans une liste de valeurs (`array`). Et bien apparemment c'est possible 🎉 

- https://github.com/frictionlessdata/framework/issues/759
- https://git.opendatafrance.net/validata/validata-core/-/issues/18

**Comment by ColinMaudry** [comment]
C'était je crois le principal bloquage pour passer des JSON schema à TableSchema ?

**Comment by vmttn** [comment]
ça et la gestion des datapackages, mais il y en aura peut-être d'autres
